spring:
  profiles:
    active: private
  datasource:
    url: ${url}
    username: ${username_}
    password: ${password}
    driver-class-name: ${driver-class-name}

  main:
    allow-circular-references: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        physical_naming_strategy: com.farmted.authservice.global.config.CustomCamelCaseToSnakeAndLowerCaseStrategy
    show-sql: true
    hibernate:
      ddl-auto: create

  #Redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 5986