server:
  port: 9090

# Swagger
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # Database
  datasource:
    driver-class-name: ${driver-class-name}
    url: ${url}
    username: ${_username}
    password: ${password}
    # Uncomment the line below if you want to set a different password
    # password: 001112

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    register-with-eureka: true # 유레카 서버에 등록하기
    fetch-registry: true # 유레카 서버에서 서버 상태 지속적 감시
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka # 타켓 유레카 서버

  # 인스턴스별로 유레카에 보여지는 표기를 다르게 설정함
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}