server:
  port: 8000
spring:
  application:
    name: gateway-server
  profiles:
    active: gateway
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter  # 추후에 사용할 전역 필터 틀
          args:
            message: Global Filter Default Message Test
            pre: true
            post: true
      routes: # 개별 마이크로서비스 정보를 routes에 기입함
        - id: board-service
          uri: lb://board-service
          predicates:
            - Path=/board-service/**
          filters:
            - JwtTokenFilter
        - id: pass-service
          uri: lb://pass-service
          predicates:
            - Path=/pass-service/**
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/member-service/**
          filters:
            - JwtTokenFilter
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product-service/**
          filters:
            - JwtTokenFilter
        - id: auction-service
          uri: lb://auction-service
          predicates:
            - Path=/auction-service/**
          filters:
            - JwtTokenFilter
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/comment-service/**
          filters:
            - JwtTokenFilter