
spring:
  application:
    name: auction-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/farmted
    username: root
    password: 1234

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        physical_naming_strategy: com.farmted.auctionservice.config.CustomCamelCaseToSnakeAndLowerCaseStrategy
    hibernate:
      ddl-auto: create

server:
  port: 8082
