spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: ENC(SsVWZpxAzcEkFBdQoXE8Pro4E7M6hFafZKonzQN1TmE33Q9c2fY3xcn7rXBEv5W+2UID/9yPr3i7ButUzjPAfg==)
#          basedir: ./repo
server:
  port: 9999