spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/farmtedPlaydata/farmted-Repo.git
          default-label: fix68
          search-paths: config-files/**
server:
  port: 18888